library(neuralnet)
library(MonoPoly)
library(polynom)
source("~/R/ageing/functions/profile.r")
load("~/R/ageing/datasets/rheumatoid_arthritis/males/vec_age_male_blood_controls.r")
load("~/R/ageing/datasets/rheumatoid_arthritis/males/blood_controls_mvalues_male_probes_removed.r")
setwd("~/R/ageing/datasets/rheumatoid_arthritis/males")
print("start profile")
profile(vec_age = vec_age_male_blood_controls, mvalues = blood_controls_mvalues_male_preprocessed, alpha = 0.5, rss = 100)
