library(neuralnet)
library(MonoPoly)
library(polynom)
source("~/R/ageing/functions/profile.r")
load("~/R/ageing/datasets/rheumatoid_arthritis/females/vec_age_female_controls.r")
load("~/R/ageing/datasets/rheumatoid_arthritis/females/blood_controls_mvalues_female_probes_removed.r")
setwd("~/R/ageing/datasets/rheumatoid_arthritis/females")
print("start profile")
profile(vec_age = vec_age_female_controls, mvalues = blood_controls_mvalues_female_preprocessed, alpha = 0.5, rss = 100)
